/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FloatOnTopPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var OPACITY_PRESETS = {
  "Opaque (100%)": 1,
  "Barely there (95%)": 0.95,
  "Light (90%)": 0.9,
  "Medium (80%)": 0.8,
  "Heavy (70%)": 0.7
};
var DEFAULT_SETTINGS = {
  alwaysOnTop: false,
  opacity: 1
};
function getWindow() {
  try {
    const { remote } = require("electron");
    return remote.getCurrentWindow();
  } catch (e) {
    console.error("Float on Top: Could not access Electron window", e);
    return null;
  }
}
var FloatOnTopPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.ribbonIconEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.ribbonIconEl = this.addRibbonIcon(
      "pin",
      "Toggle Float on Top",
      () => {
        this.toggleAlwaysOnTop();
      }
    );
    this.updateRibbonIcon();
    this.addCommand({
      id: "toggle-always-on-top",
      name: "Toggle always on top",
      callback: () => {
        this.toggleAlwaysOnTop();
      }
    });
    this.addCommand({
      id: "cycle-opacity-preset",
      name: "Cycle opacity preset",
      callback: () => {
        this.cycleOpacityPreset();
      }
    });
    this.applyWindowState();
    this.addSettingTab(new FloatOnTopSettingTab(this.app, this));
  }
  onunload() {
    const win = getWindow();
    if (win) {
      win.setAlwaysOnTop(false);
      win.setOpacity(1);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  applyWindowState() {
    const win = getWindow();
    if (!win)
      return;
    win.setAlwaysOnTop(this.settings.alwaysOnTop);
    win.setOpacity(this.settings.opacity);
  }
  toggleAlwaysOnTop() {
    this.settings.alwaysOnTop = !this.settings.alwaysOnTop;
    const win = getWindow();
    if (win) {
      win.setAlwaysOnTop(this.settings.alwaysOnTop);
    }
    this.updateRibbonIcon();
    this.saveSettings();
    new import_obsidian.Notice(
      this.settings.alwaysOnTop ? "Obsidian is now floating on top" : "Obsidian is no longer floating on top"
    );
  }
  setOpacity(value) {
    this.settings.opacity = value;
    const win = getWindow();
    if (win) {
      win.setOpacity(value);
    }
    this.saveSettings();
  }
  cycleOpacityPreset() {
    const presetValues = Object.values(OPACITY_PRESETS);
    const presetNames = Object.keys(OPACITY_PRESETS);
    const currentIndex = presetValues.findIndex(
      (v) => Math.abs(v - this.settings.opacity) < 0.01
    );
    const nextIndex = (currentIndex + 1) % presetValues.length;
    const nextValue = presetValues[nextIndex];
    this.setOpacity(nextValue);
    new import_obsidian.Notice(`Opacity: ${presetNames[nextIndex]}`);
  }
  updateRibbonIcon() {
    if (!this.ribbonIconEl)
      return;
    if (this.settings.alwaysOnTop) {
      this.ribbonIconEl.addClass("float-on-top-active");
      this.ribbonIconEl.setAttribute("aria-label", "Float on Top: ON \u2014 click to disable");
    } else {
      this.ribbonIconEl.removeClass("float-on-top-active");
      this.ribbonIconEl.setAttribute("aria-label", "Float on Top: OFF \u2014 click to enable");
    }
  }
};
var FloatOnTopSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Float on Top" });
    new import_obsidian.Setting(containerEl).setName("Always on top").setDesc("Keep Obsidian window above all other windows.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.alwaysOnTop).onChange(async (value) => {
        this.plugin.settings.alwaysOnTop = value;
        const win = getWindow();
        if (win)
          win.setAlwaysOnTop(value);
        this.plugin.updateRibbonIcon();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Translucency" });
    new import_obsidian.Setting(containerEl).setName("Opacity preset").setDesc("Quick-select a common opacity level.").addDropdown((dropdown) => {
      Object.entries(OPACITY_PRESETS).forEach(([label, value]) => {
        dropdown.addOption(String(value), label);
      });
      const match = Object.entries(OPACITY_PRESETS).find(
        ([, v]) => Math.abs(v - this.plugin.settings.opacity) < 0.01
      );
      dropdown.setValue(match ? String(match[1]) : String(OPACITY_PRESETS["Opaque (100%)"]));
      dropdown.onChange(async (value) => {
        const opacity = parseFloat(value);
        this.plugin.setOpacity(opacity);
        sliderEl.value = String(Math.round(opacity * 100));
        sliderValueEl.textContent = `${Math.round(opacity * 100)}%`;
      });
    });
    let sliderEl;
    let sliderValueEl;
    const sliderSetting = new import_obsidian.Setting(containerEl).setName("Fine-tune opacity").setDesc("Drag to set a custom opacity level (50\u2013100%).");
    sliderSetting.addSlider((slider) => {
      sliderEl = slider.sliderEl;
      slider.setLimits(50, 100, 1).setValue(Math.round(this.plugin.settings.opacity * 100)).setDynamicTooltip().onChange(async (value) => {
        const opacity = value / 100;
        this.plugin.setOpacity(opacity);
        sliderValueEl.textContent = `${value}%`;
      });
    });
    sliderValueEl = sliderSetting.controlEl.createSpan({
      text: `${Math.round(this.plugin.settings.opacity * 100)}%`,
      cls: "float-on-top-slider-value"
    });
  }
};
